// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	Name      string       `json:"name"`
	Url       string       `json:"url"`
	UserID    int64        `json:"user_id"`
	FetchedAt sql.NullTime `json:"fetched_at"`
}

type GooseDbVersion struct {
	ID        int32     `json:"id"`
	VersionID int64     `json:"version_id"`
	IsApplied bool      `json:"is_applied"`
	Tstamp    time.Time `json:"tstamp"`
}

type Post struct {
	ID     int64  `json:"id"`
	Title  string `json:"title"`
	Url    string `json:"url"`
	FeedID int64  `json:"feed_id"`
}

type User struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	ApiKey    string    `json:"api_key"`
}
