// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package database

import (
	"context"
)

const postCreate = `-- name: PostCreate :one
INSERT INTO "posts" (
	"title",
	"url",
	"feed_id"
)
VALUES ($1, $2, $3)
RETURNING id, title, url, feed_id
`

type PostCreateParams struct {
	Title  string `json:"title"`
	Url    string `json:"url"`
	FeedID int64  `json:"feed_id"`
}

func (q *Queries) PostCreate(ctx context.Context, arg PostCreateParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, postCreate, arg.Title, arg.Url, arg.FeedID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.FeedID,
	)
	return i, err
}
